### ISSUE TITLE
./tmp/core/static

### ISSUE THREAD

**Issue by madzul** [app-generator/cookiecutter-django#1]
when try to install/deploy using `cookiecutter -v -f https://github.com/app-generator/cookiecutter-django.git`, i got these errors:
`distutils.errors.DistutilsFileError: cannot copy tree './tmp/core/static': not a directory`

**Comment by app-generator** [comment]
Hello @madzul, 

The reported problem is not fixed in **v0.0.5**
Please update. 

Closing.
