### ISSUE TITLE
The Script crashes while trying to remove TMP folder on WINDOW

### ISSUE THREAD

**Issue by zaid-kamil** [app-generator/cookiecutter-django#2]
So i was trying to use the cookiecutter script for generating a django project. Everything goes fine, but the main problem is the script crashes while generating. It occurs at the remove tmp folder stage. Help me.
![image](https://user-images.githubusercontent.com/5492621/147351896-49dbd388-cf00-4ab2-b251-975c002dc2b0.png)

**Comment by app-generator** [comment]
Hello @zaid-kamil, 

This `known` issue is not critical and is visible only on Windows Systems. 
Let us know if the generated code works as expected. 

P.S. Thank you for using AppSeed products.
